version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db_con
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    build: .
    container_name: webapp_con
    command:  python manage.py runserver 0.0.0.0:8000 #python manage.py runserver 0.0.0.0:8000 #gunicorn --bind 0.0.0.0:8000 myproject.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  redis:
    image: "redis:alpine"
      
