version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db_con
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
        - "6543:5432"
  redis:
    container_name: redis_con
    image: "redis:alpine"
  web:
    build: .
    container_name: webapp_con
    command:  python manage.py runserver 0.0.0.0:8000 #daphne -b 0.0.0.0 -p 8000 minorproject.asgi:application #python manage.py runserver 0.0.0.0:8000 #gunicorn --bind 0.0.0.0:8000 myproject.wsgi
    volumes:
      - static:/static
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      
volumes:
  static:
      
