# Generated by Django 3.2.6 on 2021-11-08 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_activity_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
