# Generated by Django 3.2.6 on 2021-10-19 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to='icons/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Post.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='material',
            old_name='uuid',
            new_name='uuid_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.AddField(
            model_name='material',
            name='vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='vote_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_material', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_category', to='Post.category'),
        ),
    ]
