# Generated by Django 3.2.6 on 2021-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20211019_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid_id',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
