# Generated by Django 3.2.6 on 2021-10-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20211020_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='uuid_id',
            new_name='uuid',
        ),
    ]
