# Generated by Django 3.2.6 on 2021-10-30 19:54

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20211021_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.FileField(upload_to=Post.models.content_path),
        ),
    ]
