# Generated by Django 3.2.6 on 2021-11-02 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('user_avatar', models.ImageField(blank=True, upload_to='avatar/')),
                ('about', models.TextField(blank=True, max_length=120)),
                ('education_institute', models.CharField(blank=True, default='', max_length=128)),
                ('education_degree', models.CharField(blank=True, default='', max_length=64)),
                ('education_specialization', models.CharField(blank=True, default='', max_length=64)),
                ('education_fromdate', models.DateTimeField(blank=True, null=True)),
                ('education_todate', models.DateTimeField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='user_profile.Interests')),
                ('materials_claimed', models.ManyToManyField(blank=True, related_name='profiles', to='Post.Material')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
