# Generated by Django 3.2.6 on 2021-11-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='materials_claimed',
            new_name='materials_unlocked',
        ),
    ]
