# Generated by Django 3.2.6 on 2021-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20211021_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_fromdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_todate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
