# Generated by Django 3.2.6 on 2021-10-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20211025_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_degree',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_institute',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_specialization',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
