# Generated by Django 3.2.6 on 2021-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20211021_1520'),
        ('user_profile', '0008_alter_profile_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='user_profile.Interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='materials_claimed',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='Post.Material'),
        ),
    ]
