# Generated by Django 3.2.6 on 2021-10-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20211027_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatar/'),
        ),
    ]
