# Generated by Django 3.2.6 on 2021-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_profile_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
